version: '2'

services:
    peak_cam:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        #network_mode: "host"
            
        command: ros2 launch peak_cam peak_cam.launch.py
        devices:
            - /dev/bus/usb/002/009:/dev/bus/usb/002/009
            - /dev/bus/usb/002/005:/dev/bus/usb/002/005
    calibration:
        build: 
            context: ../
            dockerfile: docker/apriltag.Dockerfile
        #network_mode: "host"

        # command: ros2 run apriltag_ros apriltag_node --ros-args \
        #             -r image_rect:=/peak_cam/image_raw \
        #             -r camera_info:=/peak_cam/camera_info \
        #             --params-file `ros2 pkg prefix apriltag_ros`/share/apriltag_ros/cfg/tags_36h11.yaml

    # realsense:
    #     build:
    #         context: ../
    #         dockerfile: docker/realsense.Dockerfile

    #     devices:
    #         - /dev/bus/usb/002/120:/dev/bus/usb/002/120
