version: '2'

services:
    peak_cam:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        #network_mode: "host"
            
        command: ros2 launch peak_cam peak_cam.launch.py
        devices:
            - /dev/bus/usb/002/003:/dev/bus/usb/002/003
            - /dev/bus/usb/002/004:/dev/bus/usb/002/004
            - /dev/bus/usb/002/005:/dev/bus/usb/002/005
    # ros_bridge:
    #     build: 
    #         context: ../
    #         dockerfile: docker/ros1_bridge_bas_jammy.Dockerfile
    #     #network_mode: "host"

    #     command: ros2 run ros1_bridge dynamic_bridge --bridge-all-topics