version: '2'

services:
    peak_cam:
        build:
            context: ../
            dockerfile: docker/Dockerfile
            
        command: ros2 launch peak_cam peak_cam.launch.py
        devices:
            - /dev/bus/usb/003/006:/dev/bus/usb/003/006