version: '2'

services:
    peak_cam:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        #network_mode: "host"
            
        command: ros2 launch peak_cam peak_cam.launch.py
        devices:
            - /dev/bus/usb/002/009:/dev/bus/usb/002/009
            - /dev/bus/usb/002/005:/dev/bus/usb/002/005
    apriltag:
        build: 
            context: ../
            dockerfile: docker/apriltag.Dockerfile
        
        command: ros2 launch apriltag_ros apriltag_launch.py

    PoseTransform:
        build: 
            context: ../
            dockerfile: docker/PoseTransform.Dockerfile

        command: ros2 launch PoseTransform PoseTransform_launch.py
